[application]
name = "spectre-app"
out_dir = "dist"

[web.app]
title = "Spectre-rs Password Generator"
base_path = ""

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resource]
style = []
script = []

[web.resource.dev]
script = []
style = ["/assets/tailwind.css"]

[web]
# The port the fullstack server will listen on.
# Defaults to 8080 if not specified.
port = 3000 # Replace 3000 with your desired port number
